import type {
  DirectorReportSnapshot,
  FinanceContainer,
  FinanceInvoice,
  FinancePerson,
} from "@/lib/finance/types"

export const demoFinancePeople: FinancePerson[] = [
  {
    id: "demo-finance-user",
    fullName: "Demo Account",
    email: "account@elitemeat.local",
  },
]

export const demoFinanceInvoices: FinanceInvoice[] = [
  {
    id: "invoice-ar-demo",
    invoiceNo: "AR-DEMO-001",
    invoiceType: "AR",
    partyName: "Sungai Merah Retail",
    invoiceDate: new Date().toISOString().slice(0, 10),
    dueDate: new Date().toISOString().slice(0, 10),
    amount: 520,
    taxAmount: 0,
    totalAmount: 520,
    itemList: "Delivery invoice for outlet replenishment",
    paymentStatus: "UNPAID",
    ageDays: 0,
    agingBucket: "0-30",
    status: "SUBMITTED",
    fileId: null,
    filePath: "-",
    relatedModule: "delivery",
    reviewedByName: "-",
    approvedByName: "-",
    paidAt: null,
    notes: "Demo AR invoice",
    createdByName: "Demo Account",
    createdAt: new Date().toISOString(),
  },
  {
    id: "invoice-ap-demo",
    invoiceNo: "AP-DEMO-001",
    invoiceType: "AP",
    partyName: "Cold Chain Supplier",
    invoiceDate: new Date().toISOString().slice(0, 10),
    dueDate: new Date().toISOString().slice(0, 10),
    amount: 1280,
    taxAmount: 0,
    totalAmount: 1280,
    itemList: "Cold chain container service",
    paymentStatus: "UNPAID",
    ageDays: 0,
    agingBucket: "0-30",
    status: "ACCOUNT_REVIEWED",
    fileId: null,
    filePath: "-",
    relatedModule: "container",
    reviewedByName: "Demo Account",
    approvedByName: "-",
    paidAt: null,
    notes: "Demo AP invoice",
    createdByName: "Demo Account",
    createdAt: new Date().toISOString(),
  },
]

export const demoFinanceContainers: FinanceContainer[] = [
  {
    id: "container-demo",
    containerNo: "CONT-DEMO-001",
    supplierName: "Cold Chain Supplier",
    etaDate: new Date().toISOString().slice(0, 10),
    arrivalDate: null,
    status: "IN_TRANSIT",
    totalCost: 1280,
    currency: "MYR",
    invoiceId: "invoice-ap-demo",
    invoiceNo: "AP-DEMO-001",
    updatedByName: "Demo Account",
    notes: "Demo container",
    createdAt: new Date().toISOString(),
  },
]

export const demoDirectorReports: DirectorReportSnapshot[] = [
  {
    id: "director-report-demo",
    reportNo: "DR-DEMO-001",
    reportType: "DAILY",
    periodStart: new Date().toISOString().slice(0, 10),
    periodEnd: new Date().toISOString().slice(0, 10),
    totalSales: 189,
    cashCollected: 200,
    outstandingAr: 520,
    outstandingAp: 1280,
    stockValue: 0,
    expenseTotal: 68.9,
    generatedByName: "Demo Account",
    notes: "Demo director report",
    createdAt: new Date().toISOString(),
  },
]
