import type {
  Brand,
  BarcodeWeightRule,
  Item,
  NoBarcodeStock,
  Origin,
  StockDamageRequest,
  StockLocation,
  StockMovement,
  StockReturnSupplierRequest,
  StockTakeLine,
  StockTakeSession,
  StockUnit,
} from "@/lib/stock/types"

export const demoLocations: StockLocation[] = [
  { id: "loc-jalan-channel", name: "JALAN CHANNEL", active: true },
  { id: "loc-sungai-merah", name: "SUNGAI MERAH", active: true },
  { id: "loc-director", name: "DIRECTOR", active: true },
]

export const demoBrands: Brand[] = [
  "TICAN",
  "RIVASAM",
  "SEABOARD",
  "VAN ROOI",
  "ABC",
  "ICP",
  "LOCKS",
].map((name) => ({
  id: `brand-${name.toLowerCase().replaceAll(" ", "-")}`,
  name,
  active: true,
}))

export const demoOrigins: Origin[] = [
  "DENMARK",
  "SPAIN",
  "USA",
  "NETHERLAND",
  "BELGIUM",
  "CHINA",
].map((name) => ({
  id: `origin-${name.toLowerCase().replaceAll(" ", "-")}`,
  name,
  active: true,
}))

export const demoItems: Item[] = [
  {
    id: "item-meat-belly-boneless",
    itemCode: "0001",
    category: "MEAT",
    defaultBrandId: "brand-tican",
    section: "BELLY",
    name: "BONELESS",
    chineseName: null,
    ibanName: null,
    barcodeRequired: true,
    active: true,
    defaultLowStockLevel: 0,
  },
  {
    id: "item-meat-belly-bone-in",
    itemCode: "0002",
    category: "MEAT",
    defaultBrandId: "brand-tican",
    section: "BELLY",
    name: "BONE IN",
    chineseName: null,
    ibanName: null,
    barcodeRequired: true,
    active: true,
    defaultLowStockLevel: 0,
  },
  {
    id: "item-meat-loin-boneless",
    itemCode: "0003",
    category: "MEAT",
    defaultBrandId: "brand-seaboard",
    section: "LOIN",
    name: "BONELESS",
    chineseName: null,
    ibanName: null,
    barcodeRequired: true,
    active: true,
    defaultLowStockLevel: 0,
  },
  {
    id: "item-organs-cooked-stomach",
    itemCode: "0004",
    category: "ORGANS",
    defaultBrandId: "brand-abc",
    section: "COOKED",
    name: "STOMACH",
    chineseName: null,
    ibanName: null,
    barcodeRequired: true,
    active: true,
    defaultLowStockLevel: 0,
  },
  {
    id: "item-organs-tongue",
    itemCode: "0005",
    category: "ORGANS",
    defaultBrandId: "brand-abc",
    section: "TONGUE",
    name: "TONGUE",
    chineseName: null,
    ibanName: null,
    barcodeRequired: true,
    active: true,
    defaultLowStockLevel: 0,
  },
  {
    id: "item-processed-meatball",
    itemCode: "0006",
    category: "PROCESSED",
    defaultBrandId: null,
    section: "MEATBALL",
    name: "MEATBALL",
    chineseName: null,
    ibanName: null,
    barcodeRequired: false,
    active: true,
    defaultLowStockLevel: 0,
  },
]

export const demoUnits: StockUnit[] = [
  {
    id: "unit-001",
    barcode: "EM-BC-000001",
    itemId: "item-meat-belly-boneless",
    brandId: "brand-tican",
    originId: "origin-denmark",
    locationId: "loc-jalan-channel",
    status: "IN_STOCK",
    netWeightKg: 22.4,
    inboundSource: "supplier_import",
    batchNo: "B240610-A",
    receivedAt: "2026-06-01T08:30:00.000Z",
  },
  {
    id: "unit-002",
    barcode: "EM-BC-000002",
    itemId: "item-meat-belly-boneless",
    brandId: "brand-rivasam",
    originId: "origin-spain",
    locationId: "loc-jalan-channel",
    status: "IN_STOCK",
    netWeightKg: 19.8,
    inboundSource: "supplier_import",
    batchNo: "B240610-B",
    receivedAt: "2026-06-01T09:00:00.000Z",
  },
  {
    id: "unit-003",
    barcode: "EM-LN-000003",
    itemId: "item-meat-loin-boneless",
    brandId: "brand-seaboard",
    originId: "origin-usa",
    locationId: "loc-sungai-merah",
    status: "TRANSFER_PENDING",
    netWeightKg: 25.1,
    inboundSource: "transfer",
    batchNo: "L240603",
    receivedAt: "2026-06-03T10:20:00.000Z",
  },
  {
    id: "unit-004",
    barcode: "EM-OR-000004",
    itemId: "item-organs-tongue",
    brandId: "brand-abc",
    originId: "origin-china",
    locationId: "loc-director",
    status: "RETURNED",
    netWeightKg: 8.7,
    inboundSource: "return",
    batchNo: "O240604",
    receivedAt: "2026-06-04T13:10:00.000Z",
  },
  {
    id: "unit-age-6m",
    barcode: "EM-AGE-6M-001",
    itemId: "item-meat-loin-boneless",
    brandId: "brand-rivasam",
    originId: "origin-spain",
    locationId: "loc-jalan-channel",
    status: "IN_STOCK",
    netWeightKg: 10.25,
    inboundSource: "supplier_import",
    batchNo: "B251101-AGE",
    receivedAt: "2025-11-01T08:00:00.000Z",
  },
  {
    id: "unit-age-12m",
    barcode: "EM-AGE-12M-001",
    itemId: "item-organs-tongue",
    brandId: "brand-seaboard",
    originId: "origin-usa",
    locationId: "loc-sungai-merah",
    status: "IN_STOCK",
    netWeightKg: 8.75,
    inboundSource: "supplier_import",
    batchNo: "B250501-AGE",
    receivedAt: "2025-05-01T08:00:00.000Z",
  },
  {
    id: "unit-customer-return-inspection",
    barcode: "EM-RET-INSP-001",
    itemId: "item-meat-belly-bone-in",
    brandId: "brand-tican",
    originId: "origin-denmark",
    locationId: "loc-jalan-channel",
    status: "INSPECTION",
    netWeightKg: 11.5,
    inboundSource: "customer_return",
    batchNo: "RET-INSPECTION",
    receivedAt: "2026-06-10T11:30:00.000Z",
  },
]

export const demoBarcodeWeightRules: BarcodeWeightRule[] = [
  {
    id: "rule-belly-tican-jalan-channel",
    itemId: "item-meat-belly-boneless",
    brandId: "brand-tican",
    originId: "origin-denmark",
    locationId: null,
    barcodeWeightStart: 7,
    barcodeWeightLength: 5,
    barcodeWeightDecimals: 2,
    updatedAt: "2026-06-10T08:00:00.000Z",
  },
]

export const demoNoBarcodeStock: NoBarcodeStock[] = [
  {
    id: "nb-processed-meatball",
    itemId: "item-processed-meatball",
    brandId: null,
    originId: null,
    locationId: "loc-jalan-channel",
    quantity: 80,
    weightKg: 40,
  },
  {
    id: "nb-negative-belly-bone-in",
    itemId: "item-meat-belly-bone-in",
    brandId: "brand-tican",
    originId: "origin-denmark",
    locationId: "loc-sungai-merah",
    quantity: -2,
    weightKg: -18.5,
  },
]

export const demoMovements: StockMovement[] = [
  {
    id: "move-001",
    movementType: "INBOUND",
    stockUnitId: "unit-001",
    itemName: "MEAT / BELLY / BONELESS",
    barcode: "EM-BC-000001",
    fromLocation: "-",
    toLocation: "JALAN CHANNEL",
    quantity: 1,
    weightKg: 22.4,
    referenceNo: "GRN-1001",
    notes: "Initial inbound demo record",
    createdAt: "2026-06-01T08:30:00.000Z",
  },
  {
    id: "move-002",
    movementType: "OUTBOUND_TRANSFER",
    stockUnitId: "unit-003",
    itemName: "MEAT / LOIN / BONELESS",
    barcode: "EM-LN-000003",
    fromLocation: "SUNGAI MERAH",
    toLocation: "JALAN CHANNEL",
    quantity: 1,
    weightKg: 25.1,
    referenceNo: "TRF-2031",
    notes: "Pending transfer",
    createdAt: "2026-06-06T11:15:00.000Z",
  },
  {
    id: "move-003",
    movementType: "NO_BARCODE_INBOUND",
    stockUnitId: null,
    itemName: "PROCESSED / MEATBALL / MEATBALL",
    barcode: "-",
    fromLocation: "-",
    toLocation: "JALAN CHANNEL",
    quantity: 80,
    weightKg: 40,
    referenceNo: "NB-778",
    notes: "No-barcode stock received",
    createdAt: "2026-06-07T14:20:00.000Z",
  },
]

export const demoStockTakeSessions: StockTakeSession[] = [
  {
    id: "take-001",
    sessionNo: "ST-2026-0001",
    locationId: "loc-jalan-channel",
    locationName: "JALAN CHANNEL",
    itemId: "item-meat-belly-boneless",
    brandId: "brand-tican",
    status: "DRAFT",
    createdAt: "2026-06-09T09:00:00.000Z",
    submittedAt: null,
    managerReviewedAt: null,
    managerSignature: null,
    approvedAt: null,
    directorSignature: null,
  },
]

export const demoStockTakeLines: StockTakeLine[] = [
  {
    id: "take-line-001",
    sessionId: "take-001",
    itemId: "item-meat-belly-boneless",
    barcode: null,
    itemName: "MEAT / BELLY / BONELESS",
    systemCount: 2,
    actualCount: 2,
    varianceCount: 0,
    systemWeightKg: 42.2,
    actualWeightKg: 42.1,
    varianceWeightKg: -0.1,
    notes: "Demo counted line",
  },
]

export const demoDamageRequests: StockDamageRequest[] = [
  {
    id: "damage-001",
    requestNo: "DMG-20260612-DEMO",
    barcode: "EM-BC-000002",
    stockUnitId: "unit-002",
    itemId: "item-meat-belly-boneless",
    itemName: "MEAT / BELLY / BONELESS",
    locationId: "loc-jalan-channel",
    locationName: "JALAN CHANNEL",
    reason: "broken_packaging",
    status: "SUBMITTED",
    photoPath: "demo/damage-photo.jpg",
    notes: "Demo damage request waiting for manager review.",
    managerSignature: null,
    directorSignature: null,
    requestedAt: "2026-06-12T09:00:00.000Z",
  },
]

export const demoReturnSupplierRequests: StockReturnSupplierRequest[] = [
  {
    id: "return-supplier-001",
    requestNo: "RS-20260612-DEMO",
    barcode: "EM-AGE-6M-001",
    stockUnitId: "unit-age-6m",
    itemId: "item-meat-loin-boneless",
    itemName: "MEAT / LOIN / BONELESS",
    locationId: "loc-jalan-channel",
    locationName: "JALAN CHANNEL",
    supplierName: "Demo Supplier",
    status: "SUBMITTED",
    notes: "Demo return supplier request waiting for manager review.",
    managerSignature: null,
    requestedAt: "2026-06-12T10:00:00.000Z",
  },
]
